# Generated by Django 5.2.3 on 2025-07-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurl",
            name="shortened_url",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Shortened URL"
            ),
        ),
    ]
